module.exports = {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
      "../src/**/*.{js,ts,jsx,tsx}" // <-- add this line to include your library components
    ],
    theme: {
      extend: {},
    },
    plugins: [],
    safelist: [
      "bg-gray-700",
      "bg-gray-600",
      "bg-gray-900",
      "bg-black",
      "bg-white",
      "text-black",
      "text-white",
      "text-yellow-500",
      "bg-yellow-500",
      "hover:bg-gray-800",
      "hover:bg-gray-600",
      "flex",
      "space-x-4",
      "p-4",
      "rounded",
      "mt-2",
      "font-bold",
      "font-semibold",
      "transition-colors",
      "duration-300",
      "bg-red-100", "bg-red-200", "bg-red-400", "text-red-600", "border-red-400",
      "bg-blue-100", "bg-blue-200", "bg-blue-400", "text-blue-600", "border-blue-400",
      "bg-green-100", "bg-green-200", "bg-green-400", "text-green-600", "border-green-400",
      "bg-yellow-100", "bg-yellow-200", "bg-yellow-400", "text-yellow-600", "border-yellow-400",
      "bg-purple-100", "bg-purple-200", "bg-purple-400", "text-purple-600", "border-purple-400",
      "bg-pink-100", "bg-pink-200", "bg-pink-400", "text-pink-600", "border-pink-400",
      "hover:bg-red-200", "hover:bg-blue-200", "hover:bg-green-200", "hover:bg-yellow-200", "hover:bg-purple-200", "hover:bg-pink-200",
    ],
  }